version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: lu-fastapi-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
